#65
jordelucas/SISMAC-BACKEND pull request #70
Opened 2021-04-15 14:56 UTC by Clevinacio

2021-04-15 22:26 UTC, jordelucas requested changes

2021-04-15 22:26 UTC, jordelucas commented on src/database/migration/1618497968219-CriarAgendamento.ts
> +                            name: "id_vaga",
trocar por vaga_id

2021-04-15 22:26 UTC, jordelucas commented on src/database/migration/1618497968219-CriarAgendamento.ts
> +                }
faltou indicar que o vaga_id é foreign key

2021-04-15 22:26 UTC, jordelucas commented on src/models/Agendamento.ts
> +    id_vaga: string;
trocar por vaga_id

2021-04-16 20:07 UTC, Clevinacio commented on src/database/migration/1618497968219-CriarAgendamento.ts
> +                }
mas Foreign key de qual tabela? Não é melhor deixar só recebendo um uuid e depois verificar de onde é esse uuid com o repository das vagas?

2021-04-16 21:42 UTC, jordelucas commented on src/database/migration/1618497968219-CriarAgendamento.ts
> +                }
aaa, vc está certo. Esse campo pode remeter a duas tabelas diferentes

2021-04-16 21:43 UTC, jordelucas commented on src/database/migration/1618497968219-CriarAgendamento.ts
> +                }
eu que me equivoquei

2021-04-17 16:58 UTC, jordelucas approved these changes

2021-04-17 17:12 UTC, merged